print("Rahul","Iron Man",27,25)
print("Rahul","Iron Man",27,25,sep="   ")
print("Rahul","Iron Man",27,25,sep=",")
print("Rahul","Iron Man",27,25,sep=" , ")
print("Rahul","Iron Man",27,25,sep="|")
print("Rahul","Iron Man",27,25,sep=" | ")
print("Rahul","Iron Man",27,25,sep=" \n")
print("Rahul","Iron Man",27,25,sep=" \t")

print("Jack",25)
print("Rose",23)
print("Jack",25,end=" ")
print("Rose",23)
print("Jack",25,end="--->")
print("Rose",23)
print("Jack",25,end="\t")
print("Rose",23)
