t1=(1,2,3,4,5,)
t2=(6,7,8,9)
t3=(1,2,3,4,3,2)
print("/////////////////////////")
print(t3.count(5))
print(t3.count(4))
print(t3.count(2))
print("/////////////////////////")
print(t3.index(2))
# print(t3.index(5))    # value error
print("/////////////////////////")
print(len(t3))
print("/////////////////////////")
for i in t3:
    print(i)
print("/////////////////////////")
print(t1+t2)
print(t2*2)
print("/////////////////////////")
l=list(t1)
print(l)
print(type(l))
print("/////////////////////////")
t4=tuple(l)
print(t4)
print(type(t4))
print("/////////////////////////")